version: "3.2"
services:
  postgresql:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_DB: wd
      POSTGRES_USER: wd
      POSTGRES_PASSWORD: wd
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopsw
    command: server --console-address ":9001" /data
  stg-api:
    build:
      context: .
      args:
        - BUILD_PARAMS=-a -race
      dockerfile: docker/Dockerfile.stg
    ports:
      - "8443:8443"
    depends_on:
      - postgresql
    environment:
      DEBUG: "true"
      PORT: ":8443"
      POSTGRES_CONNSTR: "postgres://wd:wd@postgresql:5432/wd?sslmode=disable"
      MINIO_USER: minio
      MINIO_PASSWORD: miniopsw
      MINIO_ENDPOINT: "minio:9000"
      FO_BUCKET: "fo-bucket"
volumes:
  minio_storage: {}
