version: "3.2"
services:
  stg-api:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: .
      args:
        - BUILD_PARAMS=-a -race
      dockerfile: docker/Dockerfile.stg
    ports:
      - "8443:8443"
    environment:
      DEBUG: "true"
      PORT: ":8443"
      POSTGRES_CONNSTR: "postgres://wardrobe:wardrobe@host.docker.internal:5432/wardrobe?sslmode=disable"
      MINIO_USER: minio-wardrobe
      MINIO_PASSWORD: minio-wardrobe-psw
      MINIO_ENDPOINT: "172.17.0.1:9000"
      FO_BUCKET: "fo-bucket"