name: Build/Test

on:
  push:
    branches:
      - main
jobs:

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: golangci
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build services
        run: |
          go build -v ./cmd/storage

      - name: Test
        run: |
          go test -race -tags=integration ./...
